document.write('<link rel="stylesheet" type="text/css" href="../jquery/easyui-1.3.6/themes/default/easyui.css">');
document.write('<link rel="stylesheet" type="text/css" href="../jquery/easyui-1.3.6/themes/icon.css">');
document.write('<script type="text/javascript" src="../jquery/easyui-1.3.6/jquery-1.9.1.min.js"></script>');
document.write('<script type="text/javascript" src="../jquery/easyui-1.3.6/jquery.easyui.min.js"></script>');
document.write('<link rel="stylesheet" type="text/css" href="../app/css/style.css">');
document.write('<script type="text/javascript" src="../app/util/utilHelper.js"></script>');
document.write('<script type="text/javascript" src="../frame/datagrid.js"></script>');
document.write('<script type="text/javascript" src = "../js/rolemgr.js"></script>');
document.write('<script type="text/javascript" src="../js/main.js"></script>');
document.write('<script type="text/javascript" src="../app/content-mgr/column/columnMgr.js"></script>');
